/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  controversiesSidebar: [
    'intro',
    {
      type: 'category',
      label: 'A Brief Interlude',
      link: {
        type: 'doc',
        id: 'interlude/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'interlude'},
      ],
    },
    {
      type: 'category',
      label: 'Part I: Democracy Threats',
      link: {
        type: 'doc',
        id: 'democracy/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'democracy'},
      ],
    },
    {
      type: 'category',
      label: 'Part II: Character Issues',
      link: {
        type: 'doc',
        id: 'character/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'character'},
      ],
    },
    {
      type: 'category',
      label: 'Part III: Administration Chaos',
      link: {
        type: 'doc',
        id: 'administration/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'administration'},
      ],
    },
    {
      type: 'category',
      label: 'Part IV: Controversies',
      link: {
        type: 'doc',
        id: 'controversies/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'controversies'},
      ],
    },
    {
      type: 'category',
      label: 'Sources & Context',
      link: {
        type: 'doc',
        id: 'sources/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'sources'},
      ],
    },
  ],
};

module.exports = sidebars;
