/**
 * Data Sync Script
 *
 * This script copies data from the root /data directory to website/src/data
 * before building or starting the site. This ensures we have a single source
 * of truth for all controversy data in the root /data directory.
 */

const fs = require('fs');
const path = require('path');

// Paths
const rootDataDir = path.join(__dirname, '..', 'data');
const websiteDataDir = path.join(__dirname, 'src', 'data');
const rootCategoriesFile = path.join(__dirname, '..', 'categories.json');
const websiteCategoriesFile = path.join(__dirname, 'src', 'categories.json');

console.log('🔄 Syncing data from root to website...');

// Function to copy directory recursively
function copyDirectory(source, destination) {
  // Create destination directory if it doesn't exist
  if (!fs.existsSync(destination)) {
    fs.mkdirSync(destination, { recursive: true });
  }

  // Read source directory
  const entries = fs.readdirSync(source, { withFileTypes: true });

  for (const entry of entries) {
    const sourcePath = path.join(source, entry.name);
    const destPath = path.join(destination, entry.name);

    if (entry.isDirectory()) {
      // Recursively copy subdirectories
      copyDirectory(sourcePath, destPath);
    } else {
      // Copy file
      fs.copyFileSync(sourcePath, destPath);
    }
  }
}

// Function to copy a single file
function copyFile(source, destination) {
  fs.copyFileSync(source, destination);
}

// Function to generate controversy index
function generateControversyIndex() {
  const controversiesDir = path.join(websiteDataDir, 'controversies');
  const files = fs.readdirSync(controversiesDir).filter(f => f.endsWith('.json'));

  const index = [];

  for (const file of files) {
    const filePath = path.join(controversiesDir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(content);

    // Extract key metadata for the index
    index.push({
      filename: file.replace('.json', ''),
      id: data.id,
      title: data.title,
      summary: data.summary,
      primaryCategory: data.primaryCategory,
      severity: data.severity,
      timeline: data.timeline,
      date: data.date,
      specialTags: data.specialTags || []
    });
  }

  // Sort by date (newest first)
  index.sort((a, b) => {
    const dateA = new Date(a.date || '1900-01-01');
    const dateB = new Date(b.date || '1900-01-01');
    return dateB - dateA;
  });

  // Generate JavaScript module
  const indexContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by sync-data.js
 * It contains an index of all controversies for efficient loading.
 *
 * Generated: ${new Date().toISOString()}
 */

export const controversyIndex = ${JSON.stringify(index, null, 2)};

export default controversyIndex;
`;

  const indexPath = path.join(websiteDataDir, 'controversyIndex.js');
  fs.writeFileSync(indexPath, indexContent);

  return index.length;
}

try {
  // Copy controversies directory
  console.log('  📁 Copying controversies...');
  copyDirectory(rootDataDir, websiteDataDir);

  // Count files
  const controversyFiles = fs.readdirSync(path.join(websiteDataDir, 'controversies')).length;
  console.log(`  ✅ Copied ${controversyFiles} controversy files`);

  // Copy categories.json
  console.log('  📄 Copying categories.json...');
  copyFile(rootCategoriesFile, websiteCategoriesFile);
  console.log('  ✅ Copied categories.json');

  // Generate controversy index
  console.log('  📇 Generating controversy index...');
  const indexedCount = generateControversyIndex();
  console.log(`  ✅ Indexed ${indexedCount} controversies`);

  console.log('✨ Data sync complete!\n');
} catch (error) {
  console.error('❌ Error syncing data:', error.message);
  process.exit(1);
}
